// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8wESM4evFtPr5kp4jxrUcYULarQwkvhY',
    appId: '1:395705181340:web:e790c15679f9979ebc3959',
    messagingSenderId: '395705181340',
    projectId: 'farm-manager-14b',
    authDomain: 'farm-manager-14b.firebaseapp.com',
    storageBucket: 'farm-manager-14b.firebasestorage.app',
    measurementId: 'G-DDTN51FV7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3tK6DKgXuVmuuEtVuUHC4uaFN2hhRJk',
    appId: '1:395705181340:android:3e3f44c35f2a1ecfbc3959',
    messagingSenderId: '395705181340',
    projectId: 'farm-manager-14b',
    storageBucket: 'farm-manager-14b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZEWwUKCU6j8ay9VTJKJngy1Sj2NG-ceU',
    appId: '1:395705181340:ios:7d8cc377e7220837bc3959',
    messagingSenderId: '395705181340',
    projectId: 'farm-manager-14b',
    storageBucket: 'farm-manager-14b.firebasestorage.app',
    iosBundleId: 'com.example.farmManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZEWwUKCU6j8ay9VTJKJngy1Sj2NG-ceU',
    appId: '1:395705181340:ios:7d8cc377e7220837bc3959',
    messagingSenderId: '395705181340',
    projectId: 'farm-manager-14b',
    storageBucket: 'farm-manager-14b.firebasestorage.app',
    iosBundleId: 'com.example.farmManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8wESM4evFtPr5kp4jxrUcYULarQwkvhY',
    appId: '1:395705181340:web:77968ba557ccb323bc3959',
    messagingSenderId: '395705181340',
    projectId: 'farm-manager-14b',
    authDomain: 'farm-manager-14b.firebaseapp.com',
    storageBucket: 'farm-manager-14b.firebasestorage.app',
    measurementId: 'G-XXG6NTJ2YD',
  );
}
